services:
  - type: web
    name: gold-investment
    env: go
    buildCommand: "go build -o app ./cmd"
    startCommand: "./app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gold_go
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: gold_go_cache
          type: redis
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: "aB3xK9pL2mN8qR5tW7vY0zC1dF4gH6jM8n"

databases:
  - name: gold_go

redis:
  - name: gold_go_cache
